### ISSUE TITLE
Sort app list in log message

### ISSUE THREAD

**Issue by dzaslavskiy** [18F/watchtower#14]
It would be good if the app list in the log message that is produced by the app for "Unknown Apps Detected" is sorted in so that it is the same for any given set of apps detected. Currently the app list in the log message can be in any order.

**Comment by folksgl** [comment]
I agree. The output in the logs is the source of truth for the details of what Watchtower is marking as missing/unknown, so that output should be deterministic. As it stands, the missing/unknown resources are translated into string representations (for apps, it's the name of the app, for routes its <appname>:<routeURL>, and so on). A simple lexicographical sort should be able to do the trick.

I'd think adding a call to the stdlib [`sort.Strings(x []string)`](https://pkg.go.dev/sort#Strings) should be enough to add the kind of deterministic behavior we're going for. Any objections @dzaslavskiy?
